export const CONSTANTS = {
  NAVBAR: {
    NAVBAR_LINK_HOME: "NAVBAR.LINK.HOME",
    NAVBAR_LINK_EXAM: "NAVBAR.LINK.EXAM",
  },
  HOMEPAGE: {
    HOMEPAGE_HEADLINE_TITLE: "HOMEPAGE.HEADLINE.TITLE",
    HOMEPAGE_HEADLINE_SUBTITLE: "HOMEPAGE.HEADLINE.SUBTITLE",
  },
  MODULE_SELECTOR: {
    MODULE_SELECTOR_EXAM_SECTION: "MODULE_SELECTOR.EXAM_SECTION",
  },
};
