export const CONSTANTS = {
  NAVBAR: {
    NAVBAR_LINK_HOME: "NAVBAR.LINK.HOME",
    NAVBAR_LINK_EXAM: "NAVBAR.LINK.EXAM",
  },
  HOMEPAGE: {
    HOMEPAGE_HEADLINE_TITLE: "HOMEPAGE.HEADLINE.TITLE",
    HOMEPAGE_HEADLINE_SUBTITLE: "HOMEPAGE.HEADLINE.SUBTITLE",
  },
  MODULE_SELECTOR: {
    MODULE_SELECTOR_EXAM_SECTION: "MODULE_SELECTOR.EXAM_SECTION",
  },
  FOOTER: {
    FOOTER_LINKS_GITHUB: "FOOTER_LINKS.GITHUB",
    FOOTER_LINKS_DISCORD: "FOOTER_LINKS.DISCORD",
    FOOTER_LINKS_IMPRESSUM: "FOOTER_LINKS.IMPRESUM",
  },
};
